### ISSUE TITLE
Port and update some entries from textasdata.com

### ISSUE THREAD

**Issue by kbenoit** [quanteda/blog.quanteda.org#1]
Namely, this one https://github.com/textasdata/textasdata.github.io/issues/6

**Comment by ciflikli** [comment]
Just to clarify - as a new post, i.e. third blog post entry?

**Comment by kbenoit** [comment]
This would be a new post for blog.quanteda.org, and we would add a message to the front of the old post on textasdata.com that states that the code on that post is now obsolete, and the current version is on blog.quanteda.org. This ought to be .Rmd so we know it works! So:

1.  Start a new branch for this issue.
2.  Convert my original post into .Rmd, and use the code that Gabriel contributed and that is linked on 
https://github.com/textasdata/textasdata.github.io/issues/6. 
3.  Once it works, issue a PR and I will review and merge.

**Comment by stefan-mueller** [comment]
Any news on this, @ciflikli? This would be a nice first post for the blog. If I can assist you, let me know.

**Comment by ciflikli** [comment]
@stefan-mueller Sorry, for some reason after our slack chat I thought you would fix the problem with the way the text is parsed (no idea why I assumed that, as you didn't say you would). If you have the time, it would be great if you can have a look at that, otherwise I can give it a shot after Wednesday - prioritising the gui dev as we are again working with an external team of dev for three weeks.

**Comment by kbenoit** [comment]
I’ll try to fix it, in between the painful stretches of me finishing an overdue book chapter this week.
